### ISSUE TITLE
Application hangs after discovering services

### ISSUE THREAD

**Issue by bookyun** [Koteyk0o/LYWSD02MMC-Desktop-App#3]
Downloaded app to set custom time (Nepal time zone).

App found device, connected to it, starting discovering services and after 4-5 "discovering...", the application hangs.

This is on Windows 11, x64 based system.
![Uploading Screenshot 2024-01-15 145049.png…]()

**Comment by whoisnotthere** [comment]
Hi.
I am aware of this issue, which is caused by changes to the Bluetooth API in Windows 11.
Unfortunately, I do not have the time to support the app. You can either use Windows 10 or change the time zone on your phone and synchronize the clock once.

**Comment by whoisnotthere** [comment]
Check this version

https://github.com/Koteyk0o/LYWSD02MMC-Desktop-App/releases/tag/v0.5

**Comment by bookyun** [comment]
This works wonderfully.  Thank you so much.  I was really pulling out my hair because the unit doesn't support Nepal time zone (15 min offset) and the other web based tools and android based tools just try to change the time zone and doesn't really update time correctly.  Your tool actually updated the time instead of the time zone and worked beautifully.  Again, thank you so much!
